project_id = "gbiostpdhvfxpppfqskw"

[functions.track-profile-view]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-event-price]
verify_jwt = false

[functions.create-ticket-checkout]
verify_jwt = false

[functions.send-ticket-email]
verify_jwt = false
