project_id = "piofmmawwnermvaysonw"

[functions.track-profile-view]
verify_jwt = true

[functions.send-notification-email]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-event-price]
verify_jwt = true

[functions.create-ticket-checkout]
verify_jwt = false

[functions.send-showcase-welcome]
verify_jwt = true

[functions.send-password-reset]
verify_jwt = false

[functions.track-analytics-event]
verify_jwt = false
