project_id = "piofmmawwnermvaysonw"

[functions.track-profile-view]
verify_jwt = true

[functions.send-notification-email]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-event-price]
verify_jwt = true

[functions.create-ticket-checkout]
verify_jwt = false

[functions.send-showcase-welcome]
verify_jwt = true

[functions.send-password-reset]
verify_jwt = false

[functions.send-platform-invite]
verify_jwt = true

[functions.send-project-credit-invite]
verify_jwt = true

[functions.check-email-exists]
verify_jwt = false

[functions.track-analytics-event]
verify_jwt = false

[functions.approve-company-account]
verify_jwt = true

[functions.deny-company-account]
verify_jwt = true

[auth.email.template.confirmation]
subject = "Confirm your Inlight account"
content_path = "./supabase/templates/confirmation.html"
